### ISSUE TITLE
about cache option

### ISSUE THREAD

**Issue by erichuang2015** [gen1us2k/python-whois#29]
Hello

I can see there is a cache parm available for query, I am new for python  study and I can't figure out how the cache works in the gist codes, could you please provide me with a demo code for cache usage in this script

thank you

**Comment by gen1us2k** [comment]
Hey. Which cache are we talking about? Simple in-memory or dump data into file? Or we talking about storing data in engines like redis/memcached/couchbase? Can you please clarify this?

**Comment by erichuang2015** [comment]
Hello

what I mean cache is the features mentioned in readme file, it says

* possibility to cache results

I dont know how to use this cache option with this package
