### ISSUE TITLE
Solicitation

### ISSUE THREAD

**Issue by ghost** [gen1us2k/python-whois#30]
Could you add some more popular TLDs like .pt ?

**Comment by k0ste** [comment]
@RuiJardim, do you know whois server for this zone?

**Comment by ghost** [comment]
I'm sorry but my knowledge of networks is reduced.
You can't find this information publicly on the internet? Or through the IANA website.

**Comment by k0ste** [comment]
@RuiJardim I'm only find that .pt is only provide access to whois database via nic website.
