### ISSUE TITLE
some bugs about tld_regexpr and datetime

### ISSUE THREAD

**Issue by erichuang2015** [gen1us2k/python-whois#32]
When I add the newgtld .global it will consider syntax error

global = {'extend': 'tv',} 

global seems to be the keyword

and datatime formate for some tlds are illegal 

google.help and also google.link 

ValueError: Unknown date format: '2015-01-21t20:27:25.060z

**Comment by k0ste** [comment]
@erichuang2015, please test #33.

**Comment by erichuang2015** [comment]
@k0ste datetime errors fixed.
