### ISSUE TITLE
custom whois servers

### ISSUE THREAD

**Issue by erichuang2015** [gen1us2k/python-whois#34]
Hello

Since this script is based on linux whois command, some of the tlds are not supported or not works well , such as

.fun , .art .bar .ooo etc, it will throws errors

nic.fun connect: Network is unreachable

so is it possible to custom the whois servers for those tlds ?

**Comment by k0ste** [comment]
Of course, `whois.query()` support `host` argument.

**Comment by erichuang2015** [comment]
this argument is manually set everytime I make this query ?
What I think the best solution is that, when whois command failed, they will automaticaly switch to the custom whois server lists

**Comment by erichuang2015** [comment]
whois command failed for those tlds as below

.fun  connect: Network is unreachable
.art  connect: Network is unreachable
.bar  connect: Network is unreachable
.ooo  connect: Network is unreachable
.ceo  connect: Network is unreachable
.xyz  connect: Network is unreachable
.frl  connect: Network is unreachable
.ink  connect: Network is unreachable
.icu  connect: Network is unreachable
.coop  connect: Network is unreachable
.reit  connect: Network is unreachable
.rent  connect: Network is unreachable
.rest  connect: Network is unreachable
.tech  connect: Network is unreachable
.love  connect: Network is unreachable
.fans  connect: Network is unreachable
.wiki  connect: Network is unreachable
.site  connect: Network is unreachable
.best  connect: Network is unreachable
.gent  connect: Network is unreachable
.host  connect: Network is unreachable
.rugby  connect: Network is unreachable
.space  connect: Network is unreachable
.store  connect: Network is unreachable
.press  connect: Network is unreachable
.online  connect: Network is unreachable
.design  connect: Network is unreachable
.realty  connect: Network is unreachable
.website  connect: Network is unreachable
.college  connect: Network is unreachable
.tickets  connect: Network is unreachable
.theatre  connect: Network is unreachable
.storage  connect: Network is unreachable
.feedback  connect: Network is unreachable
.security  connect: Network is unreachable
.observer  connect: Network is unreachable
.protection  connect: Network is unreachable
.basketball  connect: Network is unreachable

.llc No whois server is known for this kind of object.
.charity No whois server is known for this kind of object.

**Comment by k0ste** [comment]
I think this is overhead for this library. You can make this function on your application.

**Comment by erichuang2015** [comment]
yes. I custom a list and query base on this

**Comment by k0ste** [comment]
If you don't want to do you own list - best option is a create issue or send PR to [rfc1036/whois](https://github.com/rfc1036/whois) IMHO.

**Comment by erichuang2015** [comment]
> Of course, `whois.query()` support `host` argument.

domain = whois.query('aaa.fun',host="whois.nic.fun")

I try to add the whois server, but it shows

Exception: connect: Network is unreachable

**Comment by k0ste** [comment]
Obviously this is network problem, not whois.

```
[k0ste@WorkStation ~]$ whois google.fun
Domain Name: GOOGLE.FUN
Registry Domain ID: D46266754-CNIC
Registrar WHOIS Server: whois.markmonitor.com
Registrar URL:
Updated Date: 2018-03-26T15:44:26.0Z
Creation Date: 2017-03-27T10:28:19.0Z
Registry Expiry Date: 2019-03-27T23:59:59.0Z
Registrar: MarkMonitor, Inc (TLDs)
Registrar IANA ID: 292
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Registrant Organization: Google Inc.
Registrant State/Province: CA
Registrant Country: US
Registrant Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Admin Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Tech Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Name Server: NS2.GOOGLEDOMAINS.COM
Name Server: NS4.GOOGLEDOMAINS.COM
Name Server: NS3.GOOGLEDOMAINS.COM
Name Server: NS1.GOOGLEDOMAINS.COM
DNSSEC: unsigned
Billing Email: Please query the RDDS service of the Registrar of Record identified in this output for information on how to contact the Registrant, Admin, or Tech contact of the queried domain name.
Registrar Abuse Contact Email: ccops@markmonitor.com
Registrar Abuse Contact Phone: +1.2083895740
URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of WHOIS database: 2018-10-31T03:44:27.0Z <<<

For more information on Whois status codes, please visit https://icann.org/epp

This whois service is provided by CentralNic Ltd and only contains
information pertaining to Internet domain names registered by our
our customers. By using this service you are agreeing (1) not to use any
information presented here for any purpose other than determining
ownership of domain names, (2) not to store or reproduce this data in
any way, (3) not to use any high-volume, automated, electronic processes
to obtain data from this service. Abuse of this service is monitored and
actions in contravention of these terms will result in being permanently
blacklisted. All data is (c) CentralNic Ltd https://www.centralnic.com/

Access to the whois service is rate limited. For more information, please
see https://registrar-console.centralnic.com/pub/whois_guidance.
```

**Comment by erichuang2015** [comment]
which version from your whois command ？
Version 5.1.1 for me and Centos 7 x86_64

**Comment by k0ste** [comment]
@erichuang2015 

```
[k0ste@WorkStation ~]$ whois --version
Version 5.3.2.

Report bugs to <md+whois@linux.it>.
[k0ste@WorkStation ~]$ 
```

**Comment by erichuang2015** [comment]
thanks. it seems my whois version is outdated
