### ISSUE TITLE
expiration date extract fail

### ISSUE THREAD

**Issue by erichuang2015** [gen1us2k/python-whois#35]
I am now using the latest python version Python 3.7.1 in centos 7
and I can't extract expiration date from the whois

>>> import whois
>>> domain = whois.query('google.com')
>>> print(domain.__dict__)
{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'registrant_cc': '', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': None, 'last_updated': datetime.datetime(2018, 2, 21, 18, 36, 40), 'name_servers': {'ns4.google.com', 'ns1.google.com', 'ns3.google.com', 'ns2.google.com'}}

you see 'expiration_date': None

**Comment by k0ste** [comment]
We don't have this issue or our tests:
```
--------------------------------------------------------------------------------
Domain: google.com, host: None
                name	"google.com"
           registrar	"MarkMonitor Inc."
       registrant_cc	"us"
       creation_date	"1997-09-15 04:00:00"
     expiration_date	"2020-09-13 21:00:00-07:00"
        last_updated	"2018-02-21 18:36:40"
        name_servers	"{'ns1.google.com', 'ns3.google.com', 'ns4.google.com', 'ns2.google.com'}"
--------------------------------------------------------------------------------
```

**Comment by erichuang2015** [comment]
do you have any idea why this happens for me? how can I get more details about this issue ?

**Comment by erichuang2015** [comment]
I just download the whois src from this git ,and I run the test here , it shows

Domain: google.com, host: None
        last_updated	"2018-02-21 18:36:40"
                name	"google.com"
       registrant_cc	""
       creation_date	"1997-09-15 04:00:00"
           registrar	"MarkMonitor Inc."
     expiration_date	"None"
        name_servers	"set(['ns3.google.com', 'ns4.google.com', 'ns1.google.com', 'ns2.google.com'])"
I can see the results are different from yours, I think the production package here is outdated, the newest commits are not merged

**Comment by k0ste** [comment]
All works as expected

```shell
[k0ste@WorkStation tmp]$ git clone git@github.com:gen1us2k/python-whois.git
Cloning into 'python-whois'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 443 (delta 65), reused 98 (delta 61), pack-reused 336
Receiving objects: 100% (443/443), 80.56 KiB | 743.00 KiB/s, done.
Resolving deltas: 100% (276/276), done.
[k0ste@WorkStation tmp]$ cd python-whois/
[k0ste@WorkStation python-whois]$ python2 test.py 
--------------------------------------------------------------------------------
Domain: google.com, host: None
        last_updated	"2018-02-21 18:36:40"
                name	"google.com"
       registrant_cc	"us"
       creation_date	"1997-09-15 04:00:00"
           registrar	"MarkMonitor Inc."
     expiration_date	"2020-09-13 21:00:00"
        name_servers	"set(['ns3.google.com', 'ns4.google.com', 'ns1.google.com', 'ns2.google.com'])"
--------------------------------------------------------------------------------
```

**Comment by erichuang2015** [comment]
that is so strange, I cant figure out why, I used python 3.7

**Comment by k0ste** [comment]
@erichuang2015, you definitely use python 2, because:

```python
name_servers "set(['ns3.google.com', 'ns4.google.com', 'ns1.google.com', 'ns2.google.com'])"
```

Returns as `set`.

Module works with Python 3.7 also perfectly:
```shell
[k0ste@WorkStation python-whois]$ python3 test.py 
--------------------------------------------------------------------------------
Domain: google.com, host: None
                name	"google.com"
           registrar	"MarkMonitor Inc."
       registrant_cc	"us"
       creation_date	"1997-09-15 04:00:00"
     expiration_date	"2020-09-13 21:00:00-07:00"
        last_updated	"2018-02-21 18:36:40"
        name_servers	"{'ns3.google.com', 'ns4.google.com', 'ns1.google.com', 'ns2.google.com'}"
--------------------------------------------------------------------------------
```

**Comment by erichuang2015** [comment]
I tried in different versions , and this time is 

[root@host www]# python3 index.py
{'name': 'google.com', 'registrar': 'MarkMonitor Inc.', 'registrant_cc': '', 'creation_date': datetime.datetime(1997, 9, 15, 4, 0), 'expiration_date': None, 'last_updated': datetime.datetime(2018, 2, 21, 18, 36, 40), 'name_servers': {'ns1.google.com', 'ns2.google.com', 'ns3.google.com', 'ns4.google.com'}}

I run linux whois command it shows correct whois data

[root@host www]# whois google.com
   Domain Name: GOOGLE.COM
   Registry Domain ID: 2138514_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.markmonitor.com
   Registrar URL: http://www.markmonitor.com
   Updated Date: 2018-02-21T18:36:40Z
   Creation Date: 1997-09-15T04:00:00Z
   Registry Expiry Date: 2020-09-14T04:00:00Z
   Registrar: MarkMonitor Inc.
   Registrar IANA ID: 292
   Registrar Abuse Contact Email: abusecomplaints@markmonitor.com
   Registrar Abuse Contact Phone: +1.2083895740
   Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
   Domain Status: serverDeleteProhibited https://icann.org/epp#serverDeleteProhibited
   Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
   Domain Status: serverUpdateProhibited https://icann.org/epp#serverUpdateProhibited
   Name Server: NS1.GOOGLE.COM
   Name Server: NS2.GOOGLE.COM
   Name Server: NS3.GOOGLE.COM
   Name Server: NS4.GOOGLE.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2018-11-22T05:15:35Z <<<

but this script did not extract the experation date and country code
