### ISSUE TITLE
wrong data format  get ValueError.

### ISSUE THREAD

**Issue by tangyongfeng** [gen1us2k/python-whois#36]
>>> who=whois.query('rechtsanwalt-baumann.de')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/whois/__init__.py", line 42, in query
    return Domain(pd) if pd['domain_name'][0] else None
  File "/usr/local/lib/python3.7/site-packages/whois/_3_adjust.py", line 17, in __init__
    self.last_updated = str_to_date(data['updated_date'][0])
  File "/usr/local/lib/python3.7/site-packages/whois/_3_adjust.py", line 95, in str_to_date
    raise ValueError("Unknown date format: '{0}'".format(s))
ValueError: Unknown date format: '2018-01'

**Comment by tangyongfeng** [comment]
Not a big problem. Thank you.

**Comment by k0ste** [comment]
You use a outdated version.

```
Domain: rechtsanwalt-baumann.de, host: None
                name	"rechtsanwalt-baumann.de"
           registrar	""
       registrant_cc	""
       creation_date	"None"
     expiration_date	"None"
        last_updated	"2018-05-24 16:22:37+02:00"
        name_servers	"{'ns2.mono.net', 'ns1.mono.net', 'ns3.mono.net'}"
```

**Comment by tangyongfeng** [comment]
My version: 0.7.12

> You use a outdated version.
> 
> ```
> Domain: rechtsanwalt-baumann.de, host: None
>                 name	"rechtsanwalt-baumann.de"
>            registrar	""
>        registrant_cc	""
>        creation_date	"None"
>      expiration_date	"None"
>         last_updated	"2018-05-24 16:22:37+02:00"
>         name_servers	"{'ns2.mono.net', 'ns1.mono.net', 'ns3.mono.net'}"
> ```

**Comment by k0ste** [comment]
> My version: 0.7.12

I mean `whois` version, because input data is wrong or from wrong source:

`'2018-01'`

What is your `whois --version`?

**Comment by tierpod** [comment]
Also, I found out that jwhois works better (on centos 7)
