### ISSUE TITLE
Can't use with heroku

### ISSUE THREAD

**Issue by lucasvazq** [gen1us2k/python-whois#38]
Can't replicate whois command in python version?
or include it in the source?

**Comment by k0ste** [comment]
Seems may be resolved with #48

**Comment by lucasvazq** [comment]
Hi @k0ste !

I don't remember the problem I was having, it's been a long time and I didn't leave any specifications written down either.
I'm going to close this because I'm no longer involved with this pkg and probably, as you say, this will be solved in the issue you linked (although I can't ensure you that).

**Comment by lucasvazq** [comment]
Let me apologize for this poorly documented issue. At that time I was just starting to program and I was moving around the world like a headless chicken.
